### ISSUE TITLE
MultiOutput Regression Example

### ISSUE THREAD

**Issue by HassamSheikh** [Ambrosys/glyph#71]
Hi,

I was wondering, does glyph support multioutput for symbolic regression? I can not seem to find an example for it.

Thanks

**Comment by markusabel** [comment]
Hello Hassan,

genetic programming does not allow for multi - output, since it is a 
tree-based representation of an expression.

However there is cartesian GP which does, Markus Quade has it 
implemented,
but there is no example in the examples folder. We do not have a 
schedule yet when to implement,
I will search for the reference to send you

Best regards,
Markus

**Comment by Ohjeah** [comment]
Hi, the multiple output example is here: https://github.com/Ambrosys/glyph/blob/master/examples/symbolic_regression/multiple_output.py

**Comment by HassamSheikh** [comment]
Thanks, I was wondering, if there is a shared sub-tree approach to handle this?

**Comment by Ohjeah** [comment]
We dont support shared subtrees out of the box, but you can implement it similarly to [ADFs](https://github.com/Ambrosys/glyph/blob/master/examples/symbolic_regression/motifs.py).
